CREATE TABLE `crm_broadcast` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `no` varchar(64) NOT NULL COMMENT '群发编号',
  `type` tinyint NOT NULL COMMENT '类型（1-短信 2-邮件）',
  `title` varchar(255) NOT NULL COMMENT '标题',
  `content` text NULL COMMENT '内容',
  `template_code` varchar(64) NULL COMMENT '模板编号',
  `customer_ids` text NULL COMMENT '客户ID列表（逗号分隔）',
  `customer_count` int NOT NULL DEFAULT 0 COMMENT '客户数量',
  `success_count` int NOT NULL DEFAULT 0 COMMENT '成功数量',
  `fail_count` int NOT NULL DEFAULT 0 COMMENT '失败数量',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态（0-待发送 10-发送中 20-已完成 30-发送失败）',
  `creator_user_id` bigint NOT NULL COMMENT '创建人ID',
  `creator_user_name` varchar(64) NULL COMMENT '创建人名称',
  `remark` varchar(500) NULL COMMENT '备注',
  `send_time` datetime NULL COMMENT '发送时间',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '删除标记',
  PRIMARY KEY (`id`),
  KEY `idx_no` (`no`),
  KEY `idx_type` (`type`),
  KEY `idx_status` (`status`),
  KEY `idx_creator_user_id` (`creator_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM群发记录表';