CREATE TABLE IF NOT EXISTS `crm_work_order` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` BIGINT NOT NULL COMMENT '租户ID',
  `title` VARCHAR(256) NOT NULL COMMENT '工单标题',
  `type` VARCHAR(32) DEFAULT NULL COMMENT '工单类型（字典）',
  `priority` VARCHAR(16) DEFAULT 'NORMAL' COMMENT '优先级（LOW/NORMAL/HIGH/URGENT）',
  `status` VARCHAR(32) NOT NULL COMMENT '状态（待处理/处理中/已完结/已退回）',
  `customer_id` BIGINT DEFAULT NULL COMMENT '关联客户ID',
  `assignee_id` BIGINT DEFAULT NULL COMMENT '处理人ID',
  `sla_deadline` DATETIME DEFAULT NULL COMMENT 'SLA截止时间',
  `is_sla_breached` TINYINT DEFAULT 0 COMMENT '是否超SLA',
  `content` TEXT DEFAULT NULL COMMENT '工单内容',
  `solution` TEXT DEFAULT NULL COMMENT '解决方案',
  `resolved_time` DATETIME DEFAULT NULL COMMENT '完结时间',
  `deleted` TINYINT DEFAULT 0 COMMENT '软删除',
  `create_time` DATETIME NOT NULL COMMENT '创建时间',
  `create_by` VARCHAR(64) DEFAULT NULL COMMENT '创建人',
  `update_time` DATETIME DEFAULT NULL COMMENT '更新时间',
  `update_by` VARCHAR(64) DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`id`),
  INDEX `idx_tenant_id` (`tenant_id`),
  INDEX `idx_status` (`status`),
  INDEX `idx_customer_id` (`customer_id`),
  INDEX `idx_assignee_id` (`assignee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='CRM工单表';