-- 23软4胡伟-202305566535-修改于2026.07.14
-- [ADD START] 发票表测试DDL - 2026-07-14 - 23软4胡伟-202305566535-修改于2026.07.14
-- 财务域模块单元测试表结构（H2 内存数据库，MySQL 兼容模式）

-- ========== 发票表 ==========
CREATE TABLE IF NOT EXISTS "crm_invoice" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "no" varchar(100) NOT NULL DEFAULT '',
    "customer_id" bigint DEFAULT NULL,
    "contract_id" bigint DEFAULT NULL,
    "order_id" bigint DEFAULT NULL,
    "owner_user_id" bigint DEFAULT NULL,
    "invoice_no" varchar(64) NOT NULL DEFAULT '',
    "type" tinyint NOT NULL DEFAULT 0,
    "amount" decimal(24,6) NOT NULL DEFAULT 0,
    "title" varchar(128) DEFAULT NULL,
    "tax_no" varchar(64) DEFAULT NULL,
    "status" tinyint NOT NULL DEFAULT 0,
    "issue_date" date DEFAULT NULL,
    "process_instance_id" varchar(64) DEFAULT NULL,
    "audit_status" tinyint DEFAULT NULL,
    "remark" varchar(500) DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);
-- [ADD END] 发票表测试DDL - 2026-07-14 - 23软4胡伟-202305566535-修改于2026.07.14
